### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-v7tsp#3]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by Karmpatel960** [comment]
Image is done and I attached the scrrenshort of it
![Screenshot (356)](https://user-images.githubusercontent.com/96860884/190384839-c3608fbe-f9e7-4ae2-944f-d5a7f31c3d6a.png)
